POST http://localhost:3003/client
Content-Type: application/json


{
    "nome": "Teste de mesas",
    "email": "teste@email.com",
    "contato": 1234567890,
    "senha": "senha",
    "servico": "Teste em massa",
    "responsavel": "Tester",
    "mesas": 10,
    "endereco": "Rua do teste 116, Bairro-Estado"
}


###
post http://localhost:3003/user
Content-Type: application/json


{
    "nome": "Para atualizar",
    "email": "atulize@email.com",
    "senha": "senha"
}


###
POST http://localhost:3003/client/login
Content-Type: application/json


{
    "email": "dog@email.com",
    "senha": "senha"
}


###
post http://localhost:3003/user/login
Content-Type: application/json


{
    "email": "kaah@email.com",
    "senha": "senha"
}


###
GET http://localhost:3003/clients


###
GET http://localhost:3003/client/f183aa08-a481-4b2a-a437-6cdef8360547


###
GET http://localhost:3003/user/0877c0bd-3cf2-4b95-8f6a-0accb731f842


###
DELETE http://localhost:3003/request/2074f183-46ea-4577-9e74-80244c8ec806


###
DELETE http://localhost:3003/cardapio/4ea47ca8-4390-4ef2-9c23-6936436072be


###
POST http://localhost:3003/cardapio/70d1f2da-9f27-4d81-85cb-66e404002fb0
Content-Type: application/json

{
    "nome": "Heinekei",
    "preco": 7
}


###
POST http://localhost:3003/request/53b004ac-8fe7-499d-8c21-861a39abbad1
Content-Type: application/json


{
    "user": "7a6a8e36-9f43-4312-89a3-03ae1b4172fa",
    "mesa": 2,
    "quantidade": 4
}


###
GET http://localhost:3003/client/requests/fd7e6e93-651f-43ff-95f6-ed5e45ece281


###
GET http://localhost:3003/client/place/f183aa08-a481-4b2a-a437-6cdef8360547


###
get http://localhost:3003/cardapio/user/2f926a78-689a-4c57-907f-3e9072c49fd1


###
get http://localhost:3003/cardapio/place/f183aa08-a481-4b2a-a437-6cdef8360547


###
PUT http://localhost:3003/client/09e63f63-2904-418b-86a6-ceb7e1e3ed8e
Content-Type: application/json


{
    "nome": "Teste de atulalização",
    "email": "teste@email.com",
    "endereco": "Rua tal",
    "contato": 1234567891,
    "servico": "Teste atualizado",
    "responsavel": "Tester",
    "mesas": 10
}


###
PUT http://localhost:3003/user/e98fd341-2e12-4210-b451-e77b91a56c84
Content-Type: application/json


{
    "nome": "Atualizar usuário",
    "email": "atualizar@email.com"
}


###
POST http://localhost:3003/clientauth/f183aa08-a481-4b2a-a437-6cdef8360547
Content-Type: application/json


{
    "senha": "senha"
}


###
POST http://localhost:3003/userauth/f183aa08-a481-4b2a-a437-6cdef8360547
Content-Type: application/json


{
    "senha": "senha"
}


###
DELETE http://localhost:3003/user/e98fd341-2e12-4210-b451-e77b91a56c84


###
DELETE http://localhost:3003/client/f183aa08-a481-4b2a-a437-6cdef8360547


###
POST http://localhost:3003/rescuepassword/
Content-Type: application/json


{
    "userEmail": "mesmo245@gmail.com"
}