POST http://localhost:3003/client
Content-Type: application/json


{
    "nome": "Chegue mais",
    "email": "fran@email.com",
    "senha": "senha",
    "servico": "Bar e restaurante",
    "responsavel": "Flamarion"
}


###
post http://localhost:3003/user
Content-Type: application/json


{
    "nome": "Ronaldo",
    "email": "nado@email.com",
    "senha": "senha"
}


###
POST http://localhost:3003/client/login
Content-Type: application/json


{
    "email": "dog@email.com",
    "senha": "senha"
}


###
post http://localhost:3003/user/login
Content-Type: application/json


{
    "email": "kaah@email.com",
    "senha": "senha"
}


###
GET http://localhost:3003/clients


###
GET http://localhost:3003/client/f183aa08-a481-4b2a-a437-6cdef8360547


###
GET http://localhost:3003/user/0877c0bd-3cf2-4b95-8f6a-0accb731f842


###
POST http://localhost:3003/user/client/f183aa08-a481-4b2a-a437-6cdef8360547
Content-Type: application/json


{
    "user": "bd76fe62-6dc5-4750-bb2c-50aeb30993cd"
}


###
POST http://localhost:3003/request/f183aa08-a481-4b2a-a437-6cdef8360547
Content-Type: application/json


{
    "pedido": "1 dogão e um refrigerante",
    "user": "0877c0bd-3cf2-4b95-8f6a-0accb731f842"
}


###
GET http://localhost:3003/client/requests/fd7e6e93-651f-43ff-95f6-ed5e45ece281


###
GET http://localhost:3003/client/place/f183aa08-a481-4b2a-a437-6cdef8360547


###
get http://localhost:3003/cardapio/user/2f926a78-689a-4c57-907f-3e9072c49fd1


###
get http://localhost:3003/cardapio/place/f183aa08-a481-4b2a-a437-6cdef8360547