POST http://localhost:3003/client
Content-Type: application/json


{
    "nome": "TEste de mesas",
    "email": "teste@email.com",
    "senha": "senha",
    "servico": "Bar e restaurante",
    "responsavel": "Flamarion",
    "mesas": 10
}


###
post http://localhost:3003/user
Content-Type: application/json


{
    "nome": "Para atualizar",
    "email": "atulize@email.com",
    "senha": "senha"
}


###
POST http://localhost:3003/client/login
Content-Type: application/json


{
    "email": "dog@email.com",
    "senha": "senha"
}


###
post http://localhost:3003/user/login
Content-Type: application/json


{
    "email": "kaah@email.com",
    "senha": "senha"
}


###
GET http://localhost:3003/clients


###
GET http://localhost:3003/client/f183aa08-a481-4b2a-a437-6cdef8360547


###
GET http://localhost:3003/user/0877c0bd-3cf2-4b95-8f6a-0accb731f842


###
DELETE http://localhost:3003/request/8cfe4b92-dfb5-4ee1-9a7d-4b47a9eeec27


###
DELETE http://localhost:3003/cardapio/4ea47ca8-4390-4ef2-9c23-6936436072be



###
POST http://localhost:3003/request/941a7357-0283-45dc-9839-36ea995744e9
Content-Type: application/json


{
    "pedido": "1 dogão e um refrigerante",
    "user": "0877c0bd-3cf2-4b95-8f6a-0accb731f842",
    "mesa": 2
}


###
GET http://localhost:3003/client/requests/fd7e6e93-651f-43ff-95f6-ed5e45ece281


###
GET http://localhost:3003/client/place/f183aa08-a481-4b2a-a437-6cdef8360547


###
get http://localhost:3003/cardapio/user/2f926a78-689a-4c57-907f-3e9072c49fd1


###
get http://localhost:3003/cardapio/place/f183aa08-a481-4b2a-a437-6cdef8360547


###
PUT http://localhost:3003/client/09e63f63-2904-418b-86a6-ceb7e1e3ed8e
Content-Type: application/json


{
    "nome": "Teste de atulalização",
    "email": "teste@email.com",
    "servico": "Teste atualizado",
    "responsavel": "Tester",
    "mesas": 10
}


###
PUT http://localhost:3003/user/e98fd341-2e12-4210-b451-e77b91a56c84
Content-Type: application/json


{
    "nome": "Atualizar usuário",
    "email": "atualizar@email.com"
}